return {
    Markers = {
        Enter = { id = 2, scaleX = 0.3, scaleY = 0.2, scaleZ = 0.15, red = 30, green = 150, blue = 30 },
        Exit = { id = 2, scaleX = 0.3, scaleY = 0.2, scaleZ = 0.15, red = 30, green = 150, blue = 30 },
        DeleteVehicle = { id = 2, scaleX = 0.3, scaleY = 0.2, scaleZ = 0.15, red = 150, green = 30, blue = 30 },
        CustomizationMenu = { id = 2, scaleX = 0.3, scaleY = 0.2, scaleZ = 0.15, red = 30, green = 150, blue = 30 },
        Impound = { id = 2, scaleX = 0.3, scaleY = 0.2, scaleZ = 0.15, red = 30, green = 150, blue = 30 }
    },

    VehicleScaleFormInfo = true, -- shows vehicle info (speed, traction, acceleration etc) in scaleform, will use more ms

    -- random models will be chosen from here when previewing garage
    PreviewModels = {
        "adder",
        "autarch",
        "banshee2",
        "bullet",
        "cheetah",
        "cyclone",
        "deveste",
        "emerus",
        "entity2",
        "entity3",
        "entityxf",
        "fmj",
        "furia",
        "gp1",
        "ignus",
        "infernus",
        "italigtb",
        "italigtb2",
        "krieger",
        "le7b",
        "lm87",
        "nero",
        "nero2",
        "osiris",
        "penetrator",
        "pfister811",
        "prototipo",
        "reaper",
        "s80",
        "sc1",
        "scramjet",
        "sheava",
        "sultanrs",
        "t20",
        "taipan",
        "tempesta",
        "tezeract",
        "thrax",
        "tigon",
        "torero2",
        "turismor",
        "tyrant",
        "tyrus",
        "vacca",
        "vagner",
        "vigilante",
        "visione",
        "voltic",
        "voltic2",
        "xa21",
        "zentorno",
        "zr350"
    }
}